/* menu: [ {id, title, channel}, ... ]
tvSrcKey: [ {tvSrc, tvTitle, tvChannel}, ... ] */

let
    tvSrcObj = {
        World: [
            { id: 'gCNeDWCI0vo', title: 'Al Jazeera, Qatar', channel: 'https://www.youtube.com/c/aljazeeraenglish' },
            { id: 'vOTiJkg1voo', title: 'ABC News, Australia', channel: 'https://www.youtube.com/c/NewsOnABC' },
            { id: '-mvUkiILTqI', title: 'ABC News, United States', channel: 'https://www.youtube.com/@ABCNews' },
            { id: 'XWq5kBlakcQ', title: 'CNA, Singapore', channel: 'https://www.youtube.com/user/channelnewsasia' },
            { id: 'tZT2MCYu6Zw', title: 'DW, Germany', channel: 'https://www.youtube.com/c/dwnews' },
            { id: 'pykpO5kQJ98', title: 'euronews, Portugal', channel: 'https://www.youtube.com/EuronewsUSA' },
            { id: 'Ap-UM1O9RBU', title: 'FRANCE 24, France', channel: 'https://www.youtube.com/c/FRANCE24English' },
            { id: '8WX6YL9JnLw', title: 'GB News, United Kingdom', channel: 'https://www.youtube.com/c/GBNewsOnline' },
            // { id: 'lyeyoqwXm5o', title: 'India Today, India', channel: 'https://www.youtube.com/c/indiatoday' }, // alternative of NDTV
            // { id: 'RQrLqUxw0U0', title: 'NDTV, India', channel: 'https://www.youtube.com/c/NDTV' },
            // { id: 'f0lYkdA-Gtw', title: 'NHK, Japan', channel: 'https://www.youtube.com/c/NHKWORLDJAPAN' }, // uniframeable
            // { id: 'V0I5eglJMRI', title: 'RT, Russia', channel: '' }, // blocked by YouTube, https://twitter.com/googleeurope/status/1498572529409179648
            { id: 'oJUvTVdTMyY', title: 'Sky News, United Kingdom', channel: 'https://www.youtube.com/c/SkyNews' },
            { id: '25NmPj2Vo6g', title: 'TaiwanPlus, Taiwan', channel: 'https://www.youtube.com/@TaiwanPlusLive' },
            { id: '5VF4aor94gw', title: 'TRT, Turkey', channel: 'https://www.youtube.com/c/trtworld' },
            { id: 'gadjsB5BkK4', title: 'WION, India', channel: 'https://www.youtube.com/c/WION' },
        ],

        Taiwan: [
            { id: 'oIgbl7t0S_w', title: 'CTI 中天', channel: 'https://www.youtube.com/c/ctitv' },
            { id: 'wM0g8EoUZ_E', title: 'CTS 華視', channel: 'https://www.youtube.com/c/CtsTw' },
            { id: 'TCnaIE_SAtM', title: 'CTV 中視', channel: 'https://www.youtube.com/c/twctvnews' },
            { id: 'V1p33hqPrUk', title: 'EBC 東森', channel: 'https://www.youtube.com/newsebc' },
            { id: 'WHEPzbFA3hw', title: 'EBC 東森', channel: 'https://www.youtube.com/c/57%E6%9D%B1%E6%A3%AE%E8%B2%A1%E7%B6%93%E6%96%B0%E8%81%9E' },
            { id: 'ylYJSBUgaMA', title: 'FTV 民視', channel: 'https://www.youtube.com/c/FTVLIVE' },
            { id: '6IquAgfvYmc', title: 'Global News 寰宇', channel: 'https://www.youtube.com/c/%E5%AF%B0%E5%AE%87%E6%96%B0%E8%81%9E%E9%A0%BB%E9%81%93' },
            { id: 'w87VGpgd90U', title: 'Global News 寰宇', channel: 'https://www.youtube.com/c/%E5%AF%B0%E5%AE%87%E6%96%B0%E8%81%9E%E9%A0%BB%E9%81%93' },
            { id: 'WTRQiVWK1jY', title: 'Global News 寰宇', channel: 'https://www.youtube.com/@globlemoney' },
            { id: 'pF507BLtbqU', title: 'iNEWS 三立', channel: 'https://www.youtube.com/c/setmoney159' },
            { id: '5n0y6b0Q25o', title: 'mnews 鏡視', channel: 'https://www.youtube.com/channel/UC4LjkybVKXCDlneVXlKAbmw' },
            { id: 'WIhgU_mc05A', title: 'NTDAPTV 亞太', channel: 'https://www.youtube.com/@NTDAPTV' },
            { id: 'C6gYqSHLRw4', title: 'PTS 公視', channel: 'https://www.youtube.com/c/ptslivestream' },
            { id: 'quwqlazU-c8', title: 'PTS 公視', channel: 'https://www.youtube.com/c/PNNPTS' },
            { id: '6KlRR_DGhmI', title: 'PTS 公視', channel: 'https://www.youtube.com/@ptstaigitai' },
            // { id: 'xL0ch83RAK8', title: 'TTV 台視', channel: 'https://www.youtube.com/@TTV_NEWS' }, // uniframeable
            { id: 'm_dhMSvUCIc', title: 'TVBS', channel: 'https://www.youtube.com/@TVBSNEWS01' },
        ],

        Mandarin: [
            { id: 'UuWI37iWVio', title: 'RAIN - 范曉萱' },
            { id: '2B7U5WkhOiE', title: '雪人 - 范曉萱' },
            { id: 'WUJBg0JizrQ', title: '你那好冷的小手 - 銀霞' },
            { id: 's2CE5n5W9D4', title: '偶然 - 銀霞' },
            { id: '5txyAI0kD9s', title: '偶然 - 陳秋霞' },
            { id: '-PEEXs_uQ48', title: '問 - 陳淑樺' },
            { id: 'p4YkHQrPt2I', title: '哭砂 - 黃鶯鶯' },
            { id: 'V96YjSCNJCU', title: '走在雨中 - 齊豫' },
            // { id: 'MP7j12iPb_k', title: '一串心 - 沈雁' },
            { id: 'UOaPBQM1lf0', title: '承認 - 辛曉琪' },
            { id: 'rAXmU300DRc', title: '心動 - 林曉培' },
            { id: 'Ygr1OOh8hvI', title: '愛情 - 莫文蔚' },
            { id: 'Gu_-6aEzxuA', title: '一生所愛 - 舒淇' },
            { id: 'bBsaUbUXf6Q', title: '想你會想我嗎 - 李之勤' },

            { id: 'efYrCQN0Ib0', title: '庭院深深 - 費玉清' },
            { id: 'AjitR7RZEQU', title: '一翦梅 - 費玉清' },
            { id: 'EqBAV4i7d20', title: '傳奇 - 李健' },
            { id: 'mxLAlGWQ4pM', title: '假如愛有天意 - 李健' },
            { id: 'lgpoDqqw5sg', title: '嚮往 - 李健' },
            { id: 'UsFQ9kbpQhw', title: '好久不見 - 陳奕迅' },
            { id: 'Lzb33Ku8k_w', title: '不要說話 - 陳奕迅' },
            { id: 'sR-Oyg2YSqo', title: '愛情轉移 - 陳奕迅' },
            { id: 'UehlbisT5Gs', title: '如果不是因為你 - 林志炫' },
            { id: 'DLQvYu1jwm0', title: '鱷魚的眼淚 - 林志炫' },
            { id: '4QmDKohzQdc', title: '夢田農夫 - 熊天平' },
            { id: 'N6GEbV1YZFA', title: '瘐澄慶 - 自在' },
            { id: 'T6iW90bI-RM', title: '蝴蝶來過這世界 - 梁漢文' },
            { id: '0ivNMQauscc', title: '放生 - 范逸臣' },
            { id: '9J_NxeC-NeE', title: '寂寞的季節 - 陶喆' },
            { id: 'mzSX6fnznek', title: '閃亮的日子 - 劉文正' },
            { id: 'NA4otP-v6iI', title: '無與倫比的美麗 - 蘇打綠' },

            { id: '-AJH6bDAamc', title: '冬季到台北來看雨 - 周蕙 & 楊永聰' },
            { id: 'U1_ILHivgGE', title: '流星下的願 - 張學友 & 許慧欣' },
            { id: 'n-k-_jzcp7c', title: '美麗的神話 - 孫楠 & 韓紅' },
            { id: '22b1WnBg5LA', title: '堅強的理由 - 莫文蔚 & 伍佰' },
            { id: 'ioTWIlehYXc', title: '夢田 - 齊豫 & 潘越雲' },
        ],

        Taiwanese: [
            { id: '9gnqI0ygqWw', title: '青石願 - 黃鳳儀' },
            { id: 'KEBoeE0PdJM', title: '青石願 - 黃鳳儀' },
            // { id: 'av-oi_OMM0g', title: '甘願的路 - 張涵雅' }, // official
            { id: 'jJ7DxPaXD24', title: '甘願的路 - 張涵雅' },
            { id: 'ttFL9UvmuFc', title: '相思聲聲 - 黃妃' },
            { id: 'O4vpXDfW9G8', title: '相思聲聲 - 黃妃' },
            { id: '36sZ1ubzZAk', title: '虞美人 - 黃妃' },
            { id: 'YIk9XpSlxJ8', title: '虞美人 - 黃妃' },
            { id: '--Ux4aJaVg8', title: '我愛妳，再會 - 荒山亮' },
            { id: 'ZDxyVedqjiQ', title: '我愛妳，再會 - 荒山亮' },
            { id: 'JrTl0k8YPpE', title: '大千懺 - 蓮歌子' },
            { id: '0QpGmmGUxos', title: '愛你的是我 - 荒山亮 & 麗莎' },
            { id: 'jLBn_S-f_iM', title: '愛你的是我 - 荒山亮 & 麗莎' },
            { id: 'gpwztOjPcmg', title: '愛你的是我 - 荒山亮 & 蔡佳瑩' },
            { id: 'PrwhLvMOkqE', title: '真愛只有你 - 林姍 & 傅振輝' },
            { id: 'uFwqNrOXVgI', title: '無人來作伴 - 林姍 & 翁立友' },
            { id: 'dOjt0L5KI8U', title: '愛你的代價 - 方瑞娥 & 高向鵬' },
        ],

        IU: [
            { id: 'aERrdOMxXmQ', title: 'Last Fantasy' },
            { id: 'XdPX3f58UwE', title: 'My old story' },
            { id: 'QMLHUVL4boE', title: 'You and I' },
            { id: 'cwsZWrYDY9A', title: 'Twenty-three 二十三' },
            { id: 'cJcF5V1_Kck', title: 'FRIDAY Feat. 張利貞 Of History' },
            { id: '_BR8-Qp4j5M', title: 'Through the Night 夜信' },
            { id: 'yUKP0Rht2o4', title: 'Good Day 好日子' },
            { id: 'v3-zV6wrbDU', title: 'Palette feat. G-DRAGON' },
            { id: 'emJoiIMqB58', title: '只有我不知道的事' },
            { id: 'lPffVN5lR6U', title: 'Every End of The Day 一天的盡頭' },
            { id: 'NPXVXh4HIQE', title: 'Ending Scene 這樣的Ending' },
        ],

        Exotic: [
            { id: 'NJR8Inf77Ac', title: 'IU - YOU&I (Performance ver.)' },
            { id: 'f_iQRO5BdCM', title: 'IU - YOU&I (MV)' },
            { id: 'GQt03lkFQE4', title: 'IU - Good Day' },
            { id: 'jeqdYqsrsA0', title: 'IU - Good Day (MV)' },
            { id: 'Rq8_WqE67SE', title: '神聖かまってちゃん - 裏切り者のレクイエム' },
            { id: 'rbfHY8mkhT8', title: '神聖かまってちゃん - 夕暮れの鳥' },
            { id: 'sUW4dDWiz-A', title: '神聖かまってちゃん - 夕暮れの鳥' },
            { id: 'ZRtdQ81jPUQ', title: 'YOASOBI - アイドル' },
            { id: 'SccHbM10-9w', title: 'YOASOBI - アイドル (NHK红白歌会)' },
            { id: '32b1bIz-hJE', title: 'L\'Arc～en～Ciel - Pieces' },
            { id: 'pAse1VuvcOE', title: '一生所愛 - 盧冠廷' },
            { id: '3ql6lSe1E-M', title: 'Acha Septriasa & Irwansyah - My Heart' },
        ],

        English: [
            { id: 'hT_nvWreIhg', title: 'OneRepublic - Counting Stars' },
            { id: 'RVmG_d3HKBA', title: 'MIKA - Relax, Take It Easy' },
            { id: 'jofNR_WkoCE', title: 'Ylvis - The Fox (What Does The Fox Say?)' },
            { id: 'Sz-6k8Wdm8U', title: 'Anthony Neely - Sorry That I Loved You' },
        ],

        欣學堂: [
            { id: '9oNS8FLHGWE' },
            { id: 'Cx8QCN5fGOg' },
            { id: 'fHo4cmOembI' },
            { id: '9zIbGCdWIh4' },
            { id: 'B1fUWSGvlsU' },
            { id: 's2RQuTTn7os' },
            { id: 'n-BMA_a8nM4' },
            { id: 'ZJ6ZUj8R5uQ' },
            { id: 'FHL-o1CJOnY' },
            { id: 'FCOtL6RFN4Y' },
            { id: '2bCDBwyEhkc' },
            { id: '50sSQrHMeWM' },
            { id: 'zs98k8eCrGU' },
        ],

        '８倍拉姆': [
            { id: 'pEVhv4eB8Q8' },
            { id: 'gpXy3_NdVEc' },
            { id: 'stb-BpPpJ7U' },
            { id: 'DBCIuVopaGA' },
            { id: '3OhStDNna-k' },
            { id: 'XvOAtMYTmPs' },
            { id: 'fvYT-qeZGY8' },
            { id: 'BkD2Z9gz_f8' },
        ],
    }